/*
 * Every country the panel can offer in a picker: ISO 3166-1 as CLDR knows it,
 * minus retired codes, uninhabited territories, and the three the website's own
 * dial-code table leaves out.
 *
 * Generated — do not edit by hand. Run `node scripts/generate-countries.mjs`,
 * which is also where the exclusions and the house spellings are explained.
 * Committed rather than computed at build time, so the panel's data does not
 * depend on whichever ICU the build machine happens to ship.
 */

export interface Country {
  /** ISO 3166-1 alpha-2. Also drives the flag image. */
  iso2: string
  name_en: string
  name_ar: string
}

/** Offered first: home, the Gulf, then where travellers here actually go. */
export const PREFERRED_ISO2 = ['SA', 'AE', 'KW', 'QA', 'BH', 'OM', 'EG', 'JO', 'TR', 'GB', 'US', 'FR']

export const COUNTRIES: Country[] = [
  { iso2: 'AD', name_en: 'Andorra', name_ar: 'أندورا' },
  { iso2: 'AE', name_en: 'United Arab Emirates', name_ar: 'الإمارات' },
  { iso2: 'AF', name_en: 'Afghanistan', name_ar: 'أفغانستان' },
  { iso2: 'AG', name_en: 'Antigua & Barbuda', name_ar: 'أنتيغوا وبربودا' },
  { iso2: 'AI', name_en: 'Anguilla', name_ar: 'أنغويلا' },
  { iso2: 'AL', name_en: 'Albania', name_ar: 'ألبانيا' },
  { iso2: 'AM', name_en: 'Armenia', name_ar: 'أرمينيا' },
  { iso2: 'AO', name_en: 'Angola', name_ar: 'أنغولا' },
  { iso2: 'AR', name_en: 'Argentina', name_ar: 'الأرجنتين' },
  { iso2: 'AS', name_en: 'American Samoa', name_ar: 'ساموا الأمريكية' },
  { iso2: 'AT', name_en: 'Austria', name_ar: 'النمسا' },
  { iso2: 'AU', name_en: 'Australia', name_ar: 'أستراليا' },
  { iso2: 'AW', name_en: 'Aruba', name_ar: 'أروبا' },
  { iso2: 'AX', name_en: 'Åland Islands', name_ar: 'جزر آلاند' },
  { iso2: 'AZ', name_en: 'Azerbaijan', name_ar: 'أذربيجان' },
  { iso2: 'BA', name_en: 'Bosnia and Herzegovina', name_ar: 'البوسنة والهرسك' },
  { iso2: 'BB', name_en: 'Barbados', name_ar: 'بربادوس' },
  { iso2: 'BD', name_en: 'Bangladesh', name_ar: 'بنغلاديش' },
  { iso2: 'BE', name_en: 'Belgium', name_ar: 'بلجيكا' },
  { iso2: 'BF', name_en: 'Burkina Faso', name_ar: 'بوركينا فاسو' },
  { iso2: 'BG', name_en: 'Bulgaria', name_ar: 'بلغاريا' },
  { iso2: 'BH', name_en: 'Bahrain', name_ar: 'البحرين' },
  { iso2: 'BI', name_en: 'Burundi', name_ar: 'بوروندي' },
  { iso2: 'BJ', name_en: 'Benin', name_ar: 'بنين' },
  { iso2: 'BL', name_en: 'St. Barthélemy', name_ar: 'سان بارتليمي' },
  { iso2: 'BM', name_en: 'Bermuda', name_ar: 'برمودا' },
  { iso2: 'BN', name_en: 'Brunei', name_ar: 'بروناي' },
  { iso2: 'BO', name_en: 'Bolivia', name_ar: 'بوليفيا' },
  { iso2: 'BR', name_en: 'Brazil', name_ar: 'البرازيل' },
  { iso2: 'BS', name_en: 'Bahamas', name_ar: 'جزر البهاما' },
  { iso2: 'BT', name_en: 'Bhutan', name_ar: 'بوتان' },
  { iso2: 'BW', name_en: 'Botswana', name_ar: 'بوتسوانا' },
  { iso2: 'BY', name_en: 'Belarus', name_ar: 'بيلاروس' },
  { iso2: 'BZ', name_en: 'Belize', name_ar: 'بليز' },
  { iso2: 'CA', name_en: 'Canada', name_ar: 'كندا' },
  { iso2: 'CC', name_en: 'Cocos (Keeling) Islands', name_ar: 'جزر كوكوس (كيلينغ)' },
  { iso2: 'CD', name_en: 'Congo - Kinshasa', name_ar: 'الكونغو - كينشاسا' },
  { iso2: 'CF', name_en: 'Central African Republic', name_ar: 'جمهورية أفريقيا الوسطى' },
  { iso2: 'CG', name_en: 'Congo - Brazzaville', name_ar: 'الكونغو - برازافيل' },
  { iso2: 'CH', name_en: 'Switzerland', name_ar: 'سويسرا' },
  { iso2: 'CI', name_en: 'Côte d’Ivoire', name_ar: 'ساحل العاج' },
  { iso2: 'CK', name_en: 'Cook Islands', name_ar: 'جزر كوك' },
  { iso2: 'CL', name_en: 'Chile', name_ar: 'تشيلي' },
  { iso2: 'CM', name_en: 'Cameroon', name_ar: 'الكاميرون' },
  { iso2: 'CN', name_en: 'China', name_ar: 'الصين' },
  { iso2: 'CO', name_en: 'Colombia', name_ar: 'كولومبيا' },
  { iso2: 'CR', name_en: 'Costa Rica', name_ar: 'كوستاريكا' },
  { iso2: 'CU', name_en: 'Cuba', name_ar: 'كوبا' },
  { iso2: 'CV', name_en: 'Cape Verde', name_ar: 'الرأس الأخضر' },
  { iso2: 'CW', name_en: 'Curaçao', name_ar: 'كوراساو' },
  { iso2: 'CX', name_en: 'Christmas Island', name_ar: 'جزيرة كريسماس' },
  { iso2: 'CY', name_en: 'Cyprus', name_ar: 'قبرص' },
  { iso2: 'CZ', name_en: 'Czechia', name_ar: 'التشيك' },
  { iso2: 'DE', name_en: 'Germany', name_ar: 'ألمانيا' },
  { iso2: 'DJ', name_en: 'Djibouti', name_ar: 'جيبوتي' },
  { iso2: 'DK', name_en: 'Denmark', name_ar: 'الدنمارك' },
  { iso2: 'DM', name_en: 'Dominica', name_ar: 'دومينيكا' },
  { iso2: 'DO', name_en: 'Dominican Republic', name_ar: 'جمهورية الدومينيكان' },
  { iso2: 'DZ', name_en: 'Algeria', name_ar: 'الجزائر' },
  { iso2: 'EC', name_en: 'Ecuador', name_ar: 'الإكوادور' },
  { iso2: 'EE', name_en: 'Estonia', name_ar: 'إستونيا' },
  { iso2: 'EG', name_en: 'Egypt', name_ar: 'مصر' },
  { iso2: 'ER', name_en: 'Eritrea', name_ar: 'إريتريا' },
  { iso2: 'ES', name_en: 'Spain', name_ar: 'إسبانيا' },
  { iso2: 'ET', name_en: 'Ethiopia', name_ar: 'إثيوبيا' },
  { iso2: 'FI', name_en: 'Finland', name_ar: 'فنلندا' },
  { iso2: 'FJ', name_en: 'Fiji', name_ar: 'فيجي' },
  { iso2: 'FK', name_en: 'Falkland Islands', name_ar: 'جزر فوكلاند' },
  { iso2: 'FM', name_en: 'Micronesia', name_ar: 'ميكرونيزيا' },
  { iso2: 'FO', name_en: 'Faroe Islands', name_ar: 'جزر فارو' },
  { iso2: 'FR', name_en: 'France', name_ar: 'فرنسا' },
  { iso2: 'GA', name_en: 'Gabon', name_ar: 'الغابون' },
  { iso2: 'GB', name_en: 'United Kingdom', name_ar: 'المملكة المتحدة' },
  { iso2: 'GD', name_en: 'Grenada', name_ar: 'غرينادا' },
  { iso2: 'GE', name_en: 'Georgia', name_ar: 'جورجيا' },
  { iso2: 'GF', name_en: 'French Guiana', name_ar: 'غويانا الفرنسية' },
  { iso2: 'GG', name_en: 'Guernsey', name_ar: 'غيرنزي' },
  { iso2: 'GH', name_en: 'Ghana', name_ar: 'غانا' },
  { iso2: 'GI', name_en: 'Gibraltar', name_ar: 'جبل طارق' },
  { iso2: 'GL', name_en: 'Greenland', name_ar: 'غرينلاند' },
  { iso2: 'GM', name_en: 'Gambia', name_ar: 'غامبيا' },
  { iso2: 'GN', name_en: 'Guinea', name_ar: 'غينيا' },
  { iso2: 'GP', name_en: 'Guadeloupe', name_ar: 'غوادلوب' },
  { iso2: 'GQ', name_en: 'Equatorial Guinea', name_ar: 'غينيا الاستوائية' },
  { iso2: 'GR', name_en: 'Greece', name_ar: 'اليونان' },
  { iso2: 'GT', name_en: 'Guatemala', name_ar: 'غواتيمالا' },
  { iso2: 'GU', name_en: 'Guam', name_ar: 'غوام' },
  { iso2: 'GW', name_en: 'Guinea-Bissau', name_ar: 'غينيا بيساو' },
  { iso2: 'GY', name_en: 'Guyana', name_ar: 'غيانا' },
  { iso2: 'HK', name_en: 'Hong Kong', name_ar: 'هونغ كونغ' },
  { iso2: 'HN', name_en: 'Honduras', name_ar: 'هندوراس' },
  { iso2: 'HR', name_en: 'Croatia', name_ar: 'كرواتيا' },
  { iso2: 'HT', name_en: 'Haiti', name_ar: 'هايتي' },
  { iso2: 'HU', name_en: 'Hungary', name_ar: 'المجر' },
  { iso2: 'ID', name_en: 'Indonesia', name_ar: 'إندونيسيا' },
  { iso2: 'IE', name_en: 'Ireland', name_ar: 'أيرلندا' },
  { iso2: 'IM', name_en: 'Isle of Man', name_ar: 'جزيرة مان' },
  { iso2: 'IN', name_en: 'India', name_ar: 'الهند' },
  { iso2: 'IQ', name_en: 'Iraq', name_ar: 'العراق' },
  { iso2: 'IS', name_en: 'Iceland', name_ar: 'آيسلندا' },
  { iso2: 'IT', name_en: 'Italy', name_ar: 'إيطاليا' },
  { iso2: 'JE', name_en: 'Jersey', name_ar: 'جيرسي' },
  { iso2: 'JM', name_en: 'Jamaica', name_ar: 'جامايكا' },
  { iso2: 'JO', name_en: 'Jordan', name_ar: 'الأردن' },
  { iso2: 'JP', name_en: 'Japan', name_ar: 'اليابان' },
  { iso2: 'KE', name_en: 'Kenya', name_ar: 'كينيا' },
  { iso2: 'KG', name_en: 'Kyrgyzstan', name_ar: 'قيرغيزستان' },
  { iso2: 'KH', name_en: 'Cambodia', name_ar: 'كمبوديا' },
  { iso2: 'KI', name_en: 'Kiribati', name_ar: 'كيريباتي' },
  { iso2: 'KM', name_en: 'Comoros', name_ar: 'جزر القمر' },
  { iso2: 'KN', name_en: 'St. Kitts & Nevis', name_ar: 'سانت كيتس ونيفيس' },
  { iso2: 'KR', name_en: 'South Korea', name_ar: 'كوريا الجنوبية' },
  { iso2: 'KW', name_en: 'Kuwait', name_ar: 'الكويت' },
  { iso2: 'KY', name_en: 'Cayman Islands', name_ar: 'جزر كايمان' },
  { iso2: 'KZ', name_en: 'Kazakhstan', name_ar: 'كازاخستان' },
  { iso2: 'LA', name_en: 'Laos', name_ar: 'لاوس' },
  { iso2: 'LB', name_en: 'Lebanon', name_ar: 'لبنان' },
  { iso2: 'LC', name_en: 'St. Lucia', name_ar: 'سانت لوسيا' },
  { iso2: 'LI', name_en: 'Liechtenstein', name_ar: 'ليختنشتاين' },
  { iso2: 'LK', name_en: 'Sri Lanka', name_ar: 'سريلانكا' },
  { iso2: 'LR', name_en: 'Liberia', name_ar: 'ليبيريا' },
  { iso2: 'LS', name_en: 'Lesotho', name_ar: 'ليسوتو' },
  { iso2: 'LT', name_en: 'Lithuania', name_ar: 'ليتوانيا' },
  { iso2: 'LU', name_en: 'Luxembourg', name_ar: 'لوكسمبورغ' },
  { iso2: 'LV', name_en: 'Latvia', name_ar: 'لاتفيا' },
  { iso2: 'LY', name_en: 'Libya', name_ar: 'ليبيا' },
  { iso2: 'MA', name_en: 'Morocco', name_ar: 'المغرب' },
  { iso2: 'MC', name_en: 'Monaco', name_ar: 'موناكو' },
  { iso2: 'MD', name_en: 'Moldova', name_ar: 'مولدوفا' },
  { iso2: 'ME', name_en: 'Montenegro', name_ar: 'الجبل الأسود' },
  { iso2: 'MF', name_en: 'St. Martin', name_ar: 'سان مارتن' },
  { iso2: 'MG', name_en: 'Madagascar', name_ar: 'مدغشقر' },
  { iso2: 'MH', name_en: 'Marshall Islands', name_ar: 'جزر مارشال' },
  { iso2: 'MK', name_en: 'North Macedonia', name_ar: 'مقدونيا الشمالية' },
  { iso2: 'ML', name_en: 'Mali', name_ar: 'مالي' },
  { iso2: 'MM', name_en: 'Myanmar (Burma)', name_ar: 'ميانمار (بورما)' },
  { iso2: 'MN', name_en: 'Mongolia', name_ar: 'منغوليا' },
  { iso2: 'MO', name_en: 'Macao SAR China', name_ar: 'منطقة ماكاو الإدارية الخاصة' },
  { iso2: 'MP', name_en: 'Northern Mariana Islands', name_ar: 'جزر ماريانا الشمالية' },
  { iso2: 'MQ', name_en: 'Martinique', name_ar: 'جزر المارتينيك' },
  { iso2: 'MR', name_en: 'Mauritania', name_ar: 'موريتانيا' },
  { iso2: 'MS', name_en: 'Montserrat', name_ar: 'مونتسرات' },
  { iso2: 'MT', name_en: 'Malta', name_ar: 'مالطا' },
  { iso2: 'MU', name_en: 'Mauritius', name_ar: 'موريشيوس' },
  { iso2: 'MV', name_en: 'Maldives', name_ar: 'المالديف' },
  { iso2: 'MW', name_en: 'Malawi', name_ar: 'ملاوي' },
  { iso2: 'MX', name_en: 'Mexico', name_ar: 'المكسيك' },
  { iso2: 'MY', name_en: 'Malaysia', name_ar: 'ماليزيا' },
  { iso2: 'MZ', name_en: 'Mozambique', name_ar: 'موزمبيق' },
  { iso2: 'NA', name_en: 'Namibia', name_ar: 'ناميبيا' },
  { iso2: 'NC', name_en: 'New Caledonia', name_ar: 'كاليدونيا الجديدة' },
  { iso2: 'NE', name_en: 'Niger', name_ar: 'النيجر' },
  { iso2: 'NF', name_en: 'Norfolk Island', name_ar: 'جزيرة نورفولك' },
  { iso2: 'NG', name_en: 'Nigeria', name_ar: 'نيجيريا' },
  { iso2: 'NI', name_en: 'Nicaragua', name_ar: 'نيكاراغوا' },
  { iso2: 'NL', name_en: 'Netherlands', name_ar: 'هولندا' },
  { iso2: 'NO', name_en: 'Norway', name_ar: 'النرويج' },
  { iso2: 'NP', name_en: 'Nepal', name_ar: 'نيبال' },
  { iso2: 'NR', name_en: 'Nauru', name_ar: 'ناورو' },
  { iso2: 'NU', name_en: 'Niue', name_ar: 'نيوي' },
  { iso2: 'NZ', name_en: 'New Zealand', name_ar: 'نيوزيلندا' },
  { iso2: 'OM', name_en: 'Oman', name_ar: 'عُمان' },
  { iso2: 'PA', name_en: 'Panama', name_ar: 'بنما' },
  { iso2: 'PE', name_en: 'Peru', name_ar: 'بيرو' },
  { iso2: 'PF', name_en: 'French Polynesia', name_ar: 'بولينيزيا الفرنسية' },
  { iso2: 'PG', name_en: 'Papua New Guinea', name_ar: 'بابوا غينيا الجديدة' },
  { iso2: 'PH', name_en: 'Philippines', name_ar: 'الفلبين' },
  { iso2: 'PK', name_en: 'Pakistan', name_ar: 'باكستان' },
  { iso2: 'PL', name_en: 'Poland', name_ar: 'بولندا' },
  { iso2: 'PM', name_en: 'St. Pierre & Miquelon', name_ar: 'سان بيير ومكويلون' },
  { iso2: 'PR', name_en: 'Puerto Rico', name_ar: 'بورتوريكو' },
  { iso2: 'PS', name_en: 'Palestinian Territories', name_ar: 'الأراضي الفلسطينية' },
  { iso2: 'PT', name_en: 'Portugal', name_ar: 'البرتغال' },
  { iso2: 'PW', name_en: 'Palau', name_ar: 'بالاو' },
  { iso2: 'PY', name_en: 'Paraguay', name_ar: 'باراغواي' },
  { iso2: 'QA', name_en: 'Qatar', name_ar: 'قطر' },
  { iso2: 'RE', name_en: 'Réunion', name_ar: 'روينيون' },
  { iso2: 'RO', name_en: 'Romania', name_ar: 'رومانيا' },
  { iso2: 'RS', name_en: 'Serbia', name_ar: 'صربيا' },
  { iso2: 'RU', name_en: 'Russia', name_ar: 'روسيا' },
  { iso2: 'RW', name_en: 'Rwanda', name_ar: 'رواندا' },
  { iso2: 'SA', name_en: 'Saudi Arabia', name_ar: 'السعودية' },
  { iso2: 'SB', name_en: 'Solomon Islands', name_ar: 'جزر سليمان' },
  { iso2: 'SC', name_en: 'Seychelles', name_ar: 'سيشل' },
  { iso2: 'SD', name_en: 'Sudan', name_ar: 'السودان' },
  { iso2: 'SE', name_en: 'Sweden', name_ar: 'السويد' },
  { iso2: 'SG', name_en: 'Singapore', name_ar: 'سنغافورة' },
  { iso2: 'SH', name_en: 'St. Helena', name_ar: 'سانت هيلينا' },
  { iso2: 'SI', name_en: 'Slovenia', name_ar: 'سلوفينيا' },
  { iso2: 'SK', name_en: 'Slovakia', name_ar: 'سلوفاكيا' },
  { iso2: 'SL', name_en: 'Sierra Leone', name_ar: 'سيراليون' },
  { iso2: 'SM', name_en: 'San Marino', name_ar: 'سان مارينو' },
  { iso2: 'SN', name_en: 'Senegal', name_ar: 'السنغال' },
  { iso2: 'SO', name_en: 'Somalia', name_ar: 'الصومال' },
  { iso2: 'SR', name_en: 'Suriname', name_ar: 'سورينام' },
  { iso2: 'SS', name_en: 'South Sudan', name_ar: 'جنوب السودان' },
  { iso2: 'ST', name_en: 'São Tomé & Príncipe', name_ar: 'ساو تومي وبرينسيبي' },
  { iso2: 'SV', name_en: 'El Salvador', name_ar: 'السلفادور' },
  { iso2: 'SX', name_en: 'Sint Maarten', name_ar: 'سانت مارتن' },
  { iso2: 'SY', name_en: 'Syria', name_ar: 'سوريا' },
  { iso2: 'SZ', name_en: 'Eswatini', name_ar: 'إسواتيني' },
  { iso2: 'TC', name_en: 'Turks & Caicos Islands', name_ar: 'جزر توركس وكايكوس' },
  { iso2: 'TD', name_en: 'Chad', name_ar: 'تشاد' },
  { iso2: 'TG', name_en: 'Togo', name_ar: 'توغو' },
  { iso2: 'TH', name_en: 'Thailand', name_ar: 'تايلاند' },
  { iso2: 'TJ', name_en: 'Tajikistan', name_ar: 'طاجيكستان' },
  { iso2: 'TK', name_en: 'Tokelau', name_ar: 'توكيلاو' },
  { iso2: 'TL', name_en: 'Timor-Leste', name_ar: 'تيمور - ليشتي' },
  { iso2: 'TM', name_en: 'Turkmenistan', name_ar: 'تركمانستان' },
  { iso2: 'TN', name_en: 'Tunisia', name_ar: 'تونس' },
  { iso2: 'TO', name_en: 'Tonga', name_ar: 'تونغا' },
  { iso2: 'TR', name_en: 'Türkiye', name_ar: 'تركيا' },
  { iso2: 'TT', name_en: 'Trinidad & Tobago', name_ar: 'ترينيداد وتوباغو' },
  { iso2: 'TV', name_en: 'Tuvalu', name_ar: 'توفالو' },
  { iso2: 'TW', name_en: 'Taiwan', name_ar: 'تايوان' },
  { iso2: 'TZ', name_en: 'Tanzania', name_ar: 'تنزانيا' },
  { iso2: 'UA', name_en: 'Ukraine', name_ar: 'أوكرانيا' },
  { iso2: 'UG', name_en: 'Uganda', name_ar: 'أوغندا' },
  { iso2: 'US', name_en: 'United States', name_ar: 'الولايات المتحدة' },
  { iso2: 'UY', name_en: 'Uruguay', name_ar: 'أورغواي' },
  { iso2: 'UZ', name_en: 'Uzbekistan', name_ar: 'أوزبكستان' },
  { iso2: 'VA', name_en: 'Vatican City', name_ar: 'الفاتيكان' },
  { iso2: 'VC', name_en: 'St. Vincent & Grenadines', name_ar: 'سانت فنسنت وجزر غرينادين' },
  { iso2: 'VE', name_en: 'Venezuela', name_ar: 'فنزويلا' },
  { iso2: 'VG', name_en: 'British Virgin Islands', name_ar: 'جزر فيرجن البريطانية' },
  { iso2: 'VI', name_en: 'U.S. Virgin Islands', name_ar: 'جزر فيرجن الأمريكية' },
  { iso2: 'VN', name_en: 'Vietnam', name_ar: 'فيتنام' },
  { iso2: 'VU', name_en: 'Vanuatu', name_ar: 'فانواتو' },
  { iso2: 'WF', name_en: 'Wallis & Futuna', name_ar: 'جزر والس وفوتونا' },
  { iso2: 'WS', name_en: 'Samoa', name_ar: 'ساموا' },
  { iso2: 'XK', name_en: 'Kosovo', name_ar: 'كوسوفو' },
  { iso2: 'YE', name_en: 'Yemen', name_ar: 'اليمن' },
  { iso2: 'YT', name_en: 'Mayotte', name_ar: 'مايوت' },
  { iso2: 'ZA', name_en: 'South Africa', name_ar: 'جنوب أفريقيا' },
  { iso2: 'ZM', name_en: 'Zambia', name_ar: 'زامبيا' },
  { iso2: 'ZW', name_en: 'Zimbabwe', name_ar: 'زيمبابوي' },
]

/** flagcdn serves one flag per ISO code. Used for the picker rows, and to fill
 *  in a visa country's flag when nobody has set one by hand. */
export function flagUrl(iso2: string, width = 40): string {
  return `https://flagcdn.com/w${width}/${iso2.toLowerCase()}.png`
}
